const movies = [{
  title: '12 Angry Men',
  directors: ['Sidney Lumet'],
  releaseDate: '4/10/1957',
  rating: 'Not Rated',
  runTime: '95 mins',
  genres: ['Drama'],
}, {
  title: '2001: A Space Odyssey',
  directors: ['Stanley Kubrick'],
  releaseDate: '4/3/1968',
  rating: 'G',
  runTime: '140 mins',
  genres: ['Science fiction'],
}, {
  title: 'A Clockwork Orange',
  directors: ['Stanley Kubrick'],
  releaseDate: '12/19/1971',
  rating: 'R',
  runTime: '137 mins',
  genres: ['Drama', 'Fantasy'],
}, {
  title: 'A Night At The Opera',
  directors: ['Sam Wood'],
  releaseDate: '11/15/1935',
  rating: 'Passed',
  runTime: '90 mins',
  genres: ['Comedy'],
}, {
  title: 'A Streetcar Named Desire',
  directors: ['Elia Kazan'],
  releaseDate: '3/22/1952',
  rating: 'PG',
  runTime: '125 mins',
  genres: ['Drama'],
}, {
  title: 'All About Eve',
  directors: ['Joseph L. Mankiewicz'],
  releaseDate: '10/27/1950',
  rating: 'Passed',
  runTime: '138 mins',
  genres: ['Drama'],
}, {
  title: 'All The President\'s Men',
  directors: ['Alan J. Pakula'],
  releaseDate: '4/1/1976',
  rating: 'PG',
  runTime: '136 mins',
  genres: ['Drama'],
}, {
  title: 'American Graffiti',
  directors: ['George Lucas'],
  releaseDate: '8/11/1973',
  rating: 'PG',
  runTime: '110 mins',
  genres: ['Comedy'],
}, {
  title: 'Annie Hall',
  directors: ['Woody Allen'],
  releaseDate: '4/20/1977',
  rating: 'PG',
  runTime: '94 mins',
  genres: ['Romantic comedy'],
}, {
  title: 'Apocalypse Now',
  directors: ['Francis Ford Coppola'],
  releaseDate: '8/15/1979',
  rating: 'R',
  runTime: '157 mins',
  genres: ['Drama'],
}, {
  title: 'Ben-Hur',
  directors: ['William Wyler'],
  releaseDate: '1/29/1960',
  rating: 'G',
  runTime: '212 mins',
  genres: ['Epic'],
}, {
  title: 'Blade Runner',
  directors: ['Ridley Scott'],
  releaseDate: '6/25/1982',
  rating: 'R',
  runTime: '124 mins',
  genres: ['Science fiction'],
}, {
  title: 'Bonnie And Clyde',
  directors: ['Arthur Penn'],
  releaseDate: '8/13/1967',
  rating: 'R',
  runTime: '111 mins',
  genres: ['Biography', 'Drama'],
}, {
  title: 'Bringing Up Baby',
  directors: ['Howard Hawks'],
  releaseDate: '2/18/1938',
  rating: 'Not Rated',
  runTime: '102 mins',
  genres: ['Screwball comedy'],
}, {
  title: 'Butch Cassidy And The Sundance Kid',
  directors: ['George Roy Hill'],
  releaseDate: '10/24/1969',
  rating: 'PG',
  runTime: '112 mins',
  genres: ['Comedy-drama', 'Western'],
}, {
  title: 'Cabaret',
  directors: ['Bob Fosse'],
  releaseDate: '2/13/1972',
  rating: 'PG',
  runTime: '124 mins',
  genres: ['Drama', 'Musical'],
}, {
  title: 'Casablanca',
  directors: ['Michael Curtiz'],
  releaseDate: '1/23/1943',
  rating: 'PG',
  runTime: '103 mins',
  genres: ['Romance'],
}, {
  title: 'Chinatown',
  directors: ['Roman Polanski'],
  releaseDate: '6/20/1974',
  rating: 'R',
  runTime: '132 mins',
  genres: ['Mystery', 'Romance'],
}, {
  title: 'Citizen Kane',
  directors: ['Orson Welles'],
  releaseDate: '9/5/1941',
  rating: 'PG',
  runTime: '119 mins',
  genres: ['Drama'],
}, {
  title: 'City Lights',
  directors: ['Charles Chaplin'],
  releaseDate: '3/7/1931',
  rating: 'G',
  runTime: '87 mins',
  genres: ['Comedy', 'Drama'],
}, {
  title: 'Do The Right Thing',
  directors: ['Spike Lee'],
  releaseDate: '6/30/1989',
  rating: 'R',
  runTime: '120 mins',
  genres: ['Drama'],
}, {
  title: 'Double Indemnity',
  directors: ['Billy Wilder'],
  releaseDate: '4/24/1944',
  rating: 'Passed',
  runTime: '106 mins',
  genres: ['Film noir'],
}, {
  title: 'Dr. Strangelove',
  directors: ['Stanley Kubrick'],
  releaseDate: '1/29/1964',
  rating: 'PG',
  runTime: '102 mins',
  genres: ['Dark comedy'],
}, {
  title: 'Duck Soup',
  directors: ['Leo McCarey'],
  releaseDate: '11/17/1933',
  rating: 'Not Rated',
  runTime: '80 mins',
  genres: ['Comedy'],
}, {
  title: 'E.T',
  directors: ['Steven Spielberg'],
  releaseDate: '6/11/1982',
  rating: 'PG',
  runTime: '120 mins',
  genres: ['Fantasy', 'Science fiction'],
}, {
  title: 'Easy Rider',
  directors: ['Dennis Hopper'],
  releaseDate: '7/14/1969',
  rating: 'R',
  runTime: '95 mins',
  genres: ['Drama'],
}, {
  title: 'Forrest Gump',
  directors: ['Robert Zemeckis'],
  releaseDate: '7/6/1994',
  rating: 'PG-13',
  runTime: '142 mins',
  genres: ['Comedy', 'Drama'],
}, {
  title: 'Gone With The Wind',
  directors: ['Victor Fleming', 'Sam Wood', 'George Cukor', 'Chester Franklin', 'James Fitzpatrick'],
  releaseDate: '1/17/1940',
  rating: 'Passed',
  runTime: '220 mins',
  genres: ['Romance'],
}, {
  title: 'Goodfellas',
  directors: ['Martin Scorsese'],
  releaseDate: '9/19/1990',
  rating: 'R',
  runTime: '146 mins',
  genres: ['Drama'],
}, {
  title: 'High Noon',
  directors: ['Fred Zinnemann'],
  releaseDate: '7/30/1952',
  rating: 'PG',
  runTime: '87 mins',
  genres: ['Western'],
}, {
  title: 'In The Heat Of The Night',
  directors: ['Norman Jewison'],
  releaseDate: '8/2/1967',
  rating: 'Not Rated',
  runTime: '110 mins',
  genres: ['Drama'],
}, {
  title: 'Intolerance',
  directors: ['D. W. Griffith'],
  releaseDate: '9/5/1916',
  rating: 'Passed',
  runTime: '197 mins',
  genres: ['Drama'],
}, {
  title: 'It Happened One Night',
  directors: ['Frank Capra'],
  releaseDate: '2/23/1934',
  rating: 'Not Rated',
  runTime: '105 mins',
  genres: ['Screwball comedy'],
}, {
  title: 'It\'s A Wonderful Life',
  directors: ['Frank Capra'],
  releaseDate: '1/7/1947',
  rating: 'PG',
  runTime: '132 mins',
  genres: ['Comedy', 'Drama', 'Fantasy'],
}, {
  title: 'Jaws',
  directors: ['Steven Spielberg'],
  releaseDate: '6/20/1975',
  rating: 'PG',
  runTime: '124 mins',
  genres: ['Drama'],
}, {
  title: 'King Kong',
  directors: ['Merian C. Cooper', 'Ernest B.Schoedsack'],
  releaseDate: '4/7/1933',
  rating: 'Passed',
  runTime: '110 mins',
  genres: ['Adventure', 'Horror'],
}, {
  title: 'Lawrence Of Arabia',
  directors: ['David Lean'],
  releaseDate: '12/16/1962',
  rating: 'Approved',
  runTime: '180 mins',
  genres: ['Adventure', 'Biography'],
}, {
  title: 'M*A*S*H',
  directors: ['Robert Altman'],
  releaseDate: '3/1/1970',
  rating: 'R',
  runTime: '116 mins',
  genres: ['Comedy'],
}, {
  title: 'Midnight Cowboy',
  directors: ['John Schlesinger'],
  releaseDate: '5/25/1969',
  rating: 'R',
  runTime: '113 mins',
  genres: ['Drama'],
}, {
  title: 'Modern Times',
  directors: ['Charles Chaplin'],
  releaseDate: '2/21/1936',
  rating: 'G',
  runTime: '87 mins',
  genres: ['Comedy'],
}, {
  title: 'Mr. Smith Goes to Washington',
  directors: ['Frank Capra'],
  releaseDate: '10/19/1939',
  rating: 'Not Rated',
  runTime: '130 mins',
  genres: ['Comedy', 'Drama'],
}, {
  title: 'Nashville',
  directors: ['Robert Altman'],
  releaseDate: '6/11/1975',
  rating: 'R',
  runTime: '157 mins',
  genres: ['Comedy', 'Drama', 'Musical'],
}, {
  title: 'Network',
  directors: ['Sidney Lumet'],
  releaseDate: '11/14/1976',
  rating: 'R',
  runTime: '121 mins',
  genres: ['Comedy', 'Drama'],
}, {
  title: 'North By Northwest',
  directors: ['Alfred Hitchcock'],
  releaseDate: '9/26/1959',
  rating: 'Not Rated',
  runTime: '136 mins',
  genres: ['Drama'],
}, {
  title: 'On The Waterfront',
  directors: ['Elia Kazan'],
  releaseDate: '6/22/1954',
  rating: 'Not Rated',
  runTime: '107 mins',
  genres: ['Drama'],
}, {
  title: 'One Flew Over The Cuckoo\'s Nest',
  directors: ['Milos Forman'],
  releaseDate: '11/19/1975',
  rating: 'R',
  runTime: '133 mins',
  genres: ['Drama'],
}, {
  title: 'Platoon',
  directors: ['Oliver Stone'],
  releaseDate: '12/19/1986',
  rating: 'R',
  runTime: '120 mins',
  genres: ['Drama'],
}, {
  title: 'Psycho',
  directors: ['Alfred Hitchcock'],
  releaseDate: '9/8/1960',
  rating: 'R',
  runTime: '108 mins',
  genres: ['Horror', 'Mystery', 'Thriller'],
}, {
  title: 'Pulp Fiction',
  directors: ['Quentin Tarantino'],
  releaseDate: '10/14/1994',
  rating: 'R',
  runTime: '154 mins',
  genres: ['Comedy', 'Drama'],
}, {
  title: 'Raging Bull',
  directors: ['Martin Scorsese'],
  releaseDate: '12/19/1980',
  rating: 'R',
  runTime: '129 mins',
  genres: ['Biography'],
}, {
  title: 'Raiders Of The Lost Ark',
  directors: ['Steven Spielberg'],
  releaseDate: '6/12/1981',
  rating: 'PG',
  runTime: '115 mins',
  genres: ['Adventure'],
}, {
  title: 'Rear Window',
  directors: ['Alfred Hitchcock'],
  releaseDate: '9/1/1954',
  rating: 'PG',
  runTime: '112 mins',
  genres: ['Mystery'],
}, {
  title: 'Rocky',
  directors: ['John G. Avildsen'],
  releaseDate: '12/3/1976',
  rating: 'PG',
  runTime: '121 mins',
  genres: ['Drama'],
}, {
  title: 'Saving Private Ryan',
  directors: ['Steven Spielberg'],
  releaseDate: '7/24/1998',
  rating: 'R',
  runTime: '170 mins',
  genres: ['Drama'],
}, {
  title: 'Schindler\'s List',
  directors: ['Steven Spielberg'],
  releaseDate: '12/15/1993',
  rating: 'R',
  runTime: '185 mins',
  genres: ['Drama'],
}, {
  title: 'Shane',
  directors: ['George Stevens'],
  releaseDate: '8/1/1953',
  rating: 'Not Rated',
  runTime: '118 mins',
  genres: ['Western'],
}, {
  title: 'Singin\' In The Rain',
  directors: ['Gene Kelly', 'Stanley Donen'],
  releaseDate: '4/11/1952',
  rating: 'G',
  runTime: '103 mins',
  genres: ['Musical', 'Comedy'],
}, {
  title: 'Snow White And The Seven Dwarfs',
  directors: ['William Cottrell', 'David Hand', 'Wilfred Jackson', 'Larry Morey', 'Perce Pearce', 'Ben Sharpsteen'],
  releaseDate: '2/4/1938',
  rating: 'G',
  runTime: '86 mins',
  genres: ['Musical'],
}, {
  title: 'Some Like It Hot',
  directors: ['Billy Wilder'],
  releaseDate: '4/14/1959',
  rating: 'Not Rated',
  runTime: '120 mins',
  genres: ['Comedy'],
}, {
  title: 'Sophie\'s Choice',
  directors: ['Alan J. Pakula'],
  releaseDate: '12/10/1982',
  rating: 'R',
  runTime: '157 mins',
  genres: ['Drama'],
}, {
  title: 'Spartacus',
  directors: ['Stanley Kubrick', 'Anthony Mann'],
  releaseDate: '11/17/1960',
  rating: 'PG-13',
  runTime: '195 mins',
  genres: ['Epic'],
}, {
  title: 'Star Wars',
  directors: ['George Lucas'],
  releaseDate: '5/25/1977',
  rating: 'PG',
  runTime: '123 mins',
  genres: ['Adventure', 'Science fiction'],
}, {
  title: 'Sullivan\'s Travels',
  directors: ['Preston Sturges'],
  releaseDate: '2/6/1942',
  rating: 'Not Rated',
  runTime: '91 mins',
  genres: ['Comedy', 'Drama'],
}, {
  title: 'Sunrise',
  directors: ['F.W. Murnau'],
  releaseDate: '11/4/1927',
  rating: 'Passed',
  runTime: '94 mins',
  genres: ['Drama', 'Romance'],
}, {
  title: 'Sunset Blvd',
  directors: ['Billy Wilder'],
  releaseDate: '9/29/1950',
  rating: 'Not Rated',
  runTime: '115 mins',
  genres: ['Drama'],
}, {
  title: 'Swing Time',
  directors: ['George Stevens'],
  releaseDate: '9/4/1936',
  rating: 'Not Rated',
  runTime: '103 mins',
  genres: ['Musical', 'Romantic comedy'],
}, {
  title: 'Taxi Driver',
  directors: ['Martin Scorsese'],
  releaseDate: '2/7/1976',
  rating: 'R',
  runTime: '112 mins',
  genres: ['Drama'],
}, {
  title: 'The African Queen',
  directors: ['John Huston'],
  releaseDate: '3/21/1952',
  rating: 'PG',
  runTime: '106 mins',
  genres: ['Romance'],
}, {
  title: 'The Apartment',
  directors: ['Billy Wilder'],
  releaseDate: '9/16/1960',
  rating: 'Not Rated',
  runTime: '125 mins',
  genres: ['Comedy', 'Drama'],
}, {
  title: 'The Best Years Of Our Lives',
  directors: ['William Wyler'],
  releaseDate: '5/29/1947',
  rating: 'Approved',
  runTime: '172 mins',
  genres: ['Drama'],
}, {
  title: 'The Bridge On The River Kwai',
  directors: ['David Lean'],
  releaseDate: '12/14/1957',
  rating: 'PG',
  runTime: '161 mins',
  genres: ['Drama'],
}, {
  title: 'The Deer Hunter',
  directors: ['Michael Cimino'],
  releaseDate: '12/8/1978',
  rating: 'R',
  runTime: '183 mins',
  genres: ['Drama'],
}, {
  title: 'The French Connection',
  directors: ['William Friedkin'],
  releaseDate: '10/1/1971',
  rating: 'R',
  runTime: '104 mins',
  genres: ['Drama'],
}, {
  title: 'The General',
  directors: ['Buster Keaton', 'Clyde Bruckman'],
  releaseDate: '2/5/1927',
  rating: 'Passed',
  runTime: '77 mins',
  genres: ['Comedy'],
}, {
  title: 'The Godfather',
  directors: ['Francis Ford Coppola'],
  releaseDate: '3/24/1972',
  rating: 'R',
  runTime: '177 mins',
  genres: ['Drama'],
}, {
  title: 'The Godfather Part II',
  directors: ['Francis Ford Coppola'],
  releaseDate: '12/20/1974',
  rating: 'R',
  runTime: '200 mins',
  genres: ['Drama'],
}, {
  title: 'The Gold Rush',
  directors: ['Charles Chaplin'],
  releaseDate: '8/16/1925',
  rating: 'Not Rated',
  runTime: '74 mins',
  genres: ['Comedy', 'Drama'],
}, {
  title: 'The Graduate',
  directors: ['Mike Nichols'],
  releaseDate: '12/21/1967',
  rating: 'PG',
  runTime: '105 mins',
  genres: ['Comedy', 'Drama'],
}, {
  title: 'The Grapes Of Wrath',
  directors: ['John Ford'],
  releaseDate: '3/15/1940',
  rating: 'Passed',
  runTime: '129 mins',
  genres: ['Drama'],
}, {
  title: 'The Last Picture Show',
  directors: ['Peter Bogdanovich'],
  releaseDate: '10/1/1971',
  rating: 'R',
  runTime: '118 mins',
  genres: ['Drama'],
}, {
  title: 'The Lord Of The Rings: The Fellowship Of The Ring',
  directors: ['Peter Jackson'],
  releaseDate: '12/19/2001',
  rating: 'PG-13',
  runTime: '178 mins',
  genres: ['Adventure', 'Drama', 'Fantasy'],
}, {
  title: 'The Maltese Falcon',
  directors: ['John Huston'],
  releaseDate: '10/18/1941',
  rating: 'Not Rated',
  runTime: '100 mins',
  genres: ['Drama'],
}, {
  title: 'The Philadelphia Story',
  directors: ['George Cukor'],
  releaseDate: '1/17/1941',
  rating: 'Not Rated',
  runTime: '112 mins',
  genres: ['Romantic comedy'],
}, {
  title: 'The Searchers',
  directors: ['John Ford'],
  releaseDate: '5/26/1956',
  rating: 'Passed',
  runTime: '119 mins',
  genres: ['Western'],
}, {
  title: 'The Shawshank Redemption',
  directors: ['Frank Darabont'],
  releaseDate: '10/14/1994',
  rating: 'R',
  runTime: '142 mins',
  genres: ['Drama'],
}, {
  title: 'The Silence Of The Lambs',
  directors: ['Jonathan Demme'],
  releaseDate: '2/14/1991',
  rating: 'R',
  runTime: '120 mins',
  genres: ['Drama'],
}, {
  title: 'The Sixth Sense',
  directors: ['M. Night Shyamalan'],
  releaseDate: '8/6/1999',
  rating: 'PG-13',
  runTime: '107 mins',
  genres: ['Drama', 'Mystery', 'Thriller'],
}, {
  title: 'The Sound Of Music',
  directors: ['Robert Wise'],
  releaseDate: '4/1/1965',
  rating: 'G',
  runTime: '175 mins',
  genres: ['Musical', 'Drama'],
}, {
  title: 'The Treasure Of The Sierra Madre',
  directors: ['John Huston'],
  releaseDate: '1/24/1948',
  rating: 'Passed',
  runTime: '128 mins',
  genres: ['Drama', 'Adventure'],
}, {
  title: 'The Wild Bunch',
  directors: ['Sam Peckinpah'],
  releaseDate: '6/18/1969',
  rating: 'R',
  runTime: '135 mins',
  genres: ['Western'],
}, {
  title: 'The Wizard Of Oz',
  directors: ['Victor Fleming', 'King Vidor'],
  releaseDate: '8/25/1939',
  rating: 'PG',
  runTime: '101 mins',
  genres: ['Fantasy', 'Musical'],
}, {
  title: 'Titanic',
  directors: ['James Cameron'],
  releaseDate: '12/19/1997',
  rating: 'PG-13',
  runTime: '197 mins',
  genres: ['Drama', 'Romance'],
}, {
  title: 'To Kill A Mockingbird',
  directors: ['Robert Mulligan'],
  releaseDate: '12/25/1962',
  rating: 'Not Rated',
  runTime: '129 mins',
  genres: ['Drama'],
}, {
  title: 'Tootsie',
  directors: ['Sydney Pollack'],
  releaseDate: '12/17/1982',
  rating: 'PG',
  runTime: '116 mins',
  genres: ['Comedy', 'Drama', 'Romance'],
}, {
  title: 'Toy Story',
  directors: ['John Lasseter'],
  releaseDate: '11/22/1995',
  rating: 'G',
  runTime: '81 mins',
  genres: ['Comedy'],
}, {
  title: 'Unforgiven',
  directors: ['Clint Eastwood'],
  releaseDate: '8/7/1992',
  rating: 'R',
  runTime: '130 mins',
  genres: ['Western'],
}, {
  title: 'Vertigo',
  directors: ['Alfred Hitchcock'],
  releaseDate: '5/28/1958',
  rating: 'PG',
  runTime: '120 mins',
  genres: ['Romance'],
}, {
  title: 'West Side Story',
  directors: ['Robert Wise', 'Jerome Robbins'],
  releaseDate: '12/23/1961',
  rating: 'Not Rated',
  runTime: '155 mins',
  genres: ['Drama', 'Musical'],
}, {
  title: 'Who\'s Afraid Of Virginia Woolf?',
  directors: ['Mike Nichols'],
  releaseDate: '6/22/1966',
  rating: 'Not Rated',
  runTime: '131 mins',
  genres: ['Drama'],
}, {
  title: 'Yankee Doodle Dandy',
  directors: ['Michael Curtiz'],
  releaseDate: '1/2/1943',
  rating: 'Passed',
  runTime: '126 mins',
  genres: ['Biography', 'Musical'],
}]

module.exports = movies
